---
abstract: 'Internationalizing Domain Names in Applications (UTS #46)'
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
build_requires:
  ExtUtils::CBuilder: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-IDN-Encode
no_index:
  directory:
    - eg
    - data
requires:
  Unicode::Normalize: '0'
  perl: '5.008005'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-IDN-Encode
  homepage: https://metacpan.org/release/Net-IDN-Encode
  repository: http://github.com/cfaerber/Net-IDN-Encode
version: '2.500'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
